[phases.setup]
nixPkgs = ["openjdk17"]  # Installe Java 17

[phases.build]
cmds = [
  "echo 'Listing files in src/jeu and src/affichage...'",
  "ls src/jeu/*.java",
  "ls src/affichage/*.java",
  "mkdir -p bin", 
  "javac -d bin src/jeu/*.java src/affichage/*.java"
]

[start]
cmd = "java -cp bin jeu.Server"  # Lance le serveur
