[phases.setup]
nixPkgs = ["openjdk17"] # Installe Java 17

[phases.build]
cmds = ["javac -d bin $(find src -name '*.java')"] # Compile ton code

[start]
cmd = "java -cp bin jeu.Server" # Lance le serveur
