[phases.setup]
nixPkgs = ["openjdk17"]  # Installe Java 17

[phases.build]
cmds = [
  "java -version",  # Vérifie la version de Java
  "ls -l src/jeu/",  # Liste les fichiers Java dans src/jeu/
  "ls -l src/affichage/",  # Liste les fichiers Java dans src/affichage/
  "mkdir -p bin",  # Crée le répertoire bin
  "javac -encoding UTF-8 -d bin src/jeu/*.java src/affichage/*.java"  # Compile les fichiers Java
]

[start]
cmd = "java -cp bin jeu.Server"  # Lance le serveur
