[phases.setup]
nixPkgs = ["openjdk17"] # Installe Java 17

[phases.build]
cmds = ["mkdir -p bin && javac -d bin $(ls src/jeu/*.java src/affichage/*.java)"]

[start]
cmd = "java -cp bin jeu.Server" # Lance le serveur
